### ISSUE TITLE
compilation issues

### ISSUE THREAD

**Issue by carsten-forty2** [CastXML/CastXML#37]
Hello, 

tried to compile with x86_64-pc-linux-gnu-clang-3.5.0 (and same with gcc-4.9.3)

CC=clang CXX=clang++ cmake ../CastXML/

and get:
[ 40%] Building CXX object src/CMakeFiles/castxml.dir/Output.cxx.o
x86_64-pc-linux-gnu-clang-3.5.0: warning: argument unused during compilation: '-I /home/carsten/src/gimli/thirdParty/src/castXML/build/src'
/home/carsten/src/gimli/thirdParty/src/castXML/CastXML/src/Output.cxx:311:34: error: no type named 'TypeInfo' in namespace 'clang'
  void PrintABIAttributes(clang::TypeInfo const& t);
                          ~~~~~~~^
/home/carsten/src/gimli/thirdParty/src/castXML/CastXML/src/Output.cxx:311:43: error: expected ')'
  void PrintABIAttributes(clang::TypeInfo const& t);
                                          ^
/home/carsten/src/gimli/thirdParty/src/castXML/CastXML/src/Output.cxx:311:26: note: to match this '('
  void PrintABIAttributes(clang::TypeInfo const& t);
                         ^
/home/carsten/src/gimli/thirdParty/src/castXML/CastXML/src/Output.cxx:1081:32: error: no viable conversion from 'std::pair<uint64_t, unsigned int>' to 'const clang::TypeDecl *'
      this->PrintABIAttributes(this->CTX.getTypeInfo(ty));
                               ^~~~~~~~~~~~~~~~~~~~~~~~~
/home/carsten/src/gimli/thirdParty/src/castXML/CastXML/src/Output.cxx:1076:60: note: passing argument to parameter 'd' here
void ASTVisitor::PrintABIAttributes(clang::TypeDecl const* d)
                                                           ^
/home/carsten/src/gimli/thirdParty/src/castXML/CastXML/src/Output.cxx:1087:18: error: variable has incomplete type 'void'
void ASTVisitor::PrintABIAttributes(clang::TypeInfo const& t)
                 ^
/home/carsten/src/gimli/thirdParty/src/castXML/CastXML/src/Output.cxx:1087:44: error: no member named 'TypeInfo' in namespace 'clang'
void ASTVisitor::PrintABIAttributes(clang::TypeInfo const& t)
                                    ~~~~~~~^
/home/carsten/src/gimli/thirdParty/src/castXML/CastXML/src/Output.cxx:1087:62: error: expected ';' after top level declarator
void ASTVisitor::PrintABIAttributes(clang::TypeInfo const& t)
                                                             ^
                                                             ;
6 errors generated.
src/CMakeFiles/castxml.dir/build.make:100: recipe for target 'src/CMakeFiles/castxml.dir/Output.cxx.o' failed


Bests,
Carsten

**Comment by carsten-forty2** [comment]
updated clang to 3.6.0 and everything is fine .. closed
