### ISSUE TITLE
Can't build with llvm 3.8.0 on OS X with gcc-5.3.0

### ISSUE THREAD

**Issue by carsten-forty2** [CastXML/CastXML#42]
Hi, 
I'm trying to build on OS X Darwin 15.2.0 with current:
gcc (Homebrew gcc 5.3.0) 5.3.0

Since llvm-3.6.2 leads to a lot of linker problems I tried at first bringing llvm up to date.

> llvm --with-clang --with-asan --HEAD
> /usr/local/Cellar/llvm/HEAD/bin/clang --version

clang version 3.8.0 
Target: x86_64-apple-darwin15.2.0
Thread model: posix

Cmake was run with the following options:
>  cmake -DLLVM_DIR=/usr/local/Cellar/llvm/HEAD/share/llvm/cmake/

Compilation leads to the following error:

[ 52%] Building CXX object src/CMakeFiles/castxml.dir/castxml.cxx.o
/Users/carsten/src/gi/thirdParty/src/castXML/src/castxml.cxx: In function 'int main(int, const char**)':
/Users/carsten/src/gi/thirdParty/src/castXML/src/castxml.cxx:76:3: error: 'BumpPtrStringSaver' is not a member of 'llvm'
   llvm::BumpPtrStringSaver argSaver(argSaverAlloc);
   ^
/Users/carsten/src/gi/thirdParty/src/castXML/src/castxml.cxx:81:5: error: 'argSaver' was not declared in this scope
     argSaver, llvm::cl::TokenizeGNUCommandLine, argv);
     ^
make[2]: *** [src/CMakeFiles/castxml.dir/castxml.cxx.o] Error 1
make[1]: *** [src/CMakeFiles/castxml.dir/all] Error 2
make: *** [all] Error 2

Maybe you have an idea how I can use castXML within OS X
Thanks

**Comment by bradking** [comment]
This looks like an error that was fixed by commit f49b3cd46d8082d49519e24d626aaec97610fbfb of CastXML.  What version of the CastXML source do you have checked out?

**Comment by carsten-forty2** [comment]
my fault .. sorry. I was not on master. 

I did a fresh clone and reconfigure all

>> cmake ../../src/castXML/ -DLLVM_DIR=/usr/local/Cellar/llvm/HEAD/share/llvm/cmake/
>> make

it compiles now but drop a lot of linker errors:

https://gist.github.com/carsten-forty2/cd0118d5fab652fbc369

**Comment by bradking** [comment]
Are those the same link errors you referenced for 3.6.2:

> Since llvm-3.6.2 leads to a lot of linker problems

?

CastXML must be built using the same C++ language level and standard library as LLVM/Clang was.  Homebrew likely built LLVM/Clang with the system compiler and not their own GCC.  Try building CastXML using the OS X system `cc` and `c++`.

**Comment by bradking** [comment]
FWIW, I have built CastXML with the OS X 10.11 system compiler against a Homebrew-installed LLVM/Clang 3.6.2.

**Comment by carsten-forty2** [comment]
I'm not sure if these are the same linker errors but I guess .. I cannot reproduce this at the moment.

But building with native comiler AppleClang 7.0.2.7000181 against LLVM/Clang 3.8.0 works.

Thank you

**Comment by bradking** [comment]
Great, thanks for reporting back!
