### ISSUE TITLE
When llvm-3.9-dev is detected it is assumed that the clang-3.9-dev is also available 

### ISSUE THREAD

**Issue by gerddie** [CastXML/CastXML#79]
When compiling on 75c7f16 (HEAD as of this morning) Debian with libclang-3.8 (Debian version 3.8.1-16) I get: 

    85%] Building CXX object src/CMakeFiles/castxml.dir/castxml.cxx.o
    /home/gerddie/CastXML/src/Output.cxx:21:34: fatal error: clang/AST/ASTContext.h: No such file or directory
     #include "clang/AST/ASTContext.h"
                                ^
    compilation terminated.
    /home/gerddie/CastXML/src/RunClang.cxx:24:35: fatal error: clang/AST/ASTConsumer.h: No such file or directory
     #include "clang/AST/ASTConsumer.h"
                                   ^
    compilation terminated.

The compilation works with libclang-3.9-dev (3.9.1-1) though.

Which brings me back to the issue that it would be nice to have tagged releases. It would help to clearly indicate what are the supported clang version(s) and language features. 

Best, 
Gert

**Comment by bradking** [comment]
Do you have `libclang-3.8-dev` installed?

```console
$ dpkg -S /usr/lib/llvm-3.8/include/clang/AST/ASTConsumer.h 
libclang-3.8-dev: /usr/lib/llvm-3.8/include/clang/AST/ASTConsumer.h
```

**Comment by gerddie** [comment]
Yes. it was installed, but now I've seen that the problem is actually different: 

cmake detects llvm-3.9 (which was probably pulled in by an upgrade), but doesn't check whether clang-3.9-dev is installed, and I didn't have this installed. I'll change the bug title accordingly.

**Comment by gerddie** [comment]
Given this it may actually be a Debian packaging problem.

**Comment by bradking** [comment]
I don't think there is anything wrong with Debian's packaging.  They choose to provide the Clang SDK in a separate package from the LLVM SDK.

CastXML does not know anything about distro packaging.  At most we could check earlier that the LLVM we find actually has the Clang headers.  When not found, we won't be able to give more information about how to resolve the problem though.

**Comment by gerddie** [comment]
Such a check would probably be prudent. 

About the packaging: cmake should probably not succeed if the clang-X.Y-dev files are not available, which means that the cmake files are probably in the wrong package llvm-X.Y-dev (I will report it like this in Debian).

**Comment by bradking** [comment]
Such a check could be added before the block that does `include_directories(${LLVM_INCLUDE_DIRS})`.  One would loop over the include dirs to check if any of them contains the Clang headers.
